version: '3.8'

services:
  krdv-app:
    container_name: krdv
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "4000:4000"
    expose:
      - '4000'
    volumes:
      - ./frontend/asset:/go/bin/frontend/asset
    networks: 
      - labalaba
    # network_mode: host
    environment:
      - APP_NAME=krdv
      - APP_VERSION=1.0.0
      - MODE=dev
      - PORT=4000
      - HOST=localhost:4000
      - DOMAIN=http://localhost:4000
      - WS=ws://localhost:4000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=dbkrdv
      - DB_NAME=krdv
      - DB_PORT=5432
      - TIMEZONE=Asia/Bangkok
      - SSL_MODE=disable
      - REDIS=1
      - REDIS_HOST=cachekrdv
      - REDIS_PORT=6379
      - REDIS_DB=2 
      - REDIS_USER=
      - REDIS_PASSWORD=
      - TMDB_URI=https://api.themoviedb.org
      - TMDB_IMAGE=https://image.tmdb.org/t/p/w300_and_h450_bestv2
      - TMDB_API_KEY=666e0b759c90084d5843a707b38bb607
      - TMDB_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NjZlMGI3NTljOTAwODRkNTg0M2E3MDdiMzhiYjYwNyIsInN1YiI6IjYzYTQzZjZmNjhiMWVhMDA3Yjc3M2MxYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-aOYtu7s4DeviAn2ZX0cpsn5IPH1HwZo3k6yjWOe4Gc
    depends_on:
      - pgsql
      - credis

  pgsql:
    container_name: dbkrdv
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=krdv
    ports:
      - '5435:5432'
    expose:
      - '5435'
    volumes: 
      - dpgsql:/var/lib/postgresql/data
    networks: 
      - labalaba
  
  #redis
  credis:
    container_name: cachekrdv
    image: redislabs/redismod
    restart: always
    ports:
      - '6371:6379'
    expose:
      - '6371'
    # network_mode: host
    networks: 
      - labalaba

networks:
  labalaba:
    name: labalaba
    driver: bridge

volumes:
  dpgsql:
    driver: local